# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'DnDSpells' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  

  # Pods for DnDSpells
  pod "RealmSwift", "3.17.0"
  pod 'TPKeyboardAvoiding', '1.3.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'SPStorkController', '1.6.5'
  pod 'M13Checkbox'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['Kingfisher'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'
        end
      end
    end
  end
  
end
